### ISSUE TITLE
Verions appear and disappear

### ISSUE THREAD

**Issue by SzotsGabor** [Algorhythm-sxv/Cheers#1]
I am already using 0.2.1 instead of 0.2. Now that version has been withdrawn and 0.2.2 released with exactly the same explanation as it was with 0.2.1.
What is the difference and can I safely use 0.2.2 instead of 0.2 and 0.2.1?

Gabor Szots, CCRL testing group

**Comment by Algorhythm-sxv** [comment]
Hi, sorry for the confusion. A further issue with `movestogo` time management was corrected with 0.2.2. If you are not testing with this time control 0.2.1 should work, but 0.2.2 would be preferable

**Comment by SzotsGabor** [comment]
> Hi, sorry for the confusion. A further issue with `movestogo` time management was corrected with 0.2.2. If you are not testing with this time control 0.2.1 should work, but 0.2.2 would be preferable

I am testing with 2+1 time controls. Is 0.2.2 equivalent with 0.2 strengthwise?

**Comment by Algorhythm-sxv** [comment]
0.2.2 should be slightly stronger

**Comment by Algorhythm-sxv** [comment]
[0.3.0](https://github.com/Algorhythm-sxv/Cheers/releases/tag/v0.3.0) is now the latest version, and in future all bugfixes will go in minor versions,
