### ISSUE TITLE
Illegal castling

### ISSUE THREAD

**Issue by SzotsGabor** [Algorhythm-sxv/Cheers#2]
Just noticed. Under Arena all castling moves are deemed illegal. Probable reason: short castling is written in the form e8xh8.

**Comment by SzotsGabor** [comment]
Seems like an Arena bug although I have seen it with only one other engine, Clover. E.g. sent move is e8h8 but Arena prints the PV as Ke8xh8.

**Comment by Algorhythm-sxv** [comment]
This issue has been addressed with release [0.3.0](https://github.com/Algorhythm-sxv/Cheers/releases/tag/v0.3.0)
